
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author invitado
 */
public class FrmVentana extends javax.swing.JFrame {

    /**
     * Creates new form FrmVentana
     */
    public FrmVentana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInstruccioAsignacionESA = new javax.swing.JButton();
        btnInstCondicionalSimple = new javax.swing.JButton();
        btnCondicionaldoble = new javax.swing.JButton();
        btnCondicionalMultiple = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInstruccioAsignacionESA.setText("Instruccio Asignacion ESA");
        btnInstruccioAsignacionESA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccioAsignacionESAActionPerformed(evt);
            }
        });

        btnInstCondicionalSimple.setText("Int. Condicional Simple");
        btnInstCondicionalSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstCondicionalSimpleActionPerformed(evt);
            }
        });

        btnCondicionaldoble.setText("Int. Condicional doble");
        btnCondicionaldoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCondicionaldobleActionPerformed(evt);
            }
        });

        btnCondicionalMultiple.setText("Int. Condicional Multiple");
        btnCondicionalMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCondicionalMultipleActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");

        jButton6.setText("jButton6");

        jButton7.setText("jButton7");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Hola Mundo");
        jLabel1.setIconTextGap(5);
        jLabel1.setMaximumSize(new java.awt.Dimension(259, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(btnInstruccioAsignacionESA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInstCondicionalSimple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCondicionaldoble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCondicionalMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInstruccioAsignacionESA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInstCondicionalSimple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCondicionaldoble)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCondicionalMultiple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCondicionalMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCondicionalMultipleActionPerformed
        int dia = Integer.parseInt( JOptionPane.showInputDialog(this, 
                                                "Escrive un numero entero"));
        
        String cadenaDia ="";
        
        switch (dia){
            case 1: cadenaDia += " Domingo";
                break;
            case 2: cadenaDia += " Lunes";
                break;
            case 3: cadenaDia += " Martes";
                break;
            case 4: cadenaDia += " Miercoles";
               break; 
            case 5: cadenaDia += " Jueves";
                break;
            case 6: cadenaDia += " Viernes";
                break;
            case 7: cadenaDia += " Sabado";
                break;
            default: cadenaDia += " ERROR";
        }
        JOptionPane.showMessageDialog(this, cadenaDia);
    }//GEN-LAST:event_btnCondicionalMultipleActionPerformed

    private void btnInstruccioAsignacionESAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccioAsignacionESAActionPerformed
        //llamada a una caja de dialogo de entrada.
        String nombre = JOptionPane.showInputDialog(this, "Escribe tu nombre: " );
        
        //llamada a una caja 
        String saludo = "Bienvenido " + nombre + "Adios";
        
        JOptionPane.showMessageDialog(this, saludo);
    }//GEN-LAST:event_btnInstruccioAsignacionESAActionPerformed

    private void btnInstCondicionalSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstCondicionalSimpleActionPerformed
int compra, boletos;
        
        
        
        compra = Integer.parseInt( JOptionPane.showInputDialog(this, 
                                        "¿cuál fue el monto de tu compla") );
        
        //priceso
        if( compra >= 1100 ){
            boletos = (compra-1000)/100;
            JOptionPane.showMessageDialog(this, "Obtienes " + boletos +  " boletos");
            
        }
       JOptionPane.showMessageDialog(this, "Gracias por tu compra ");
    }//GEN-LAST:event_btnInstCondicionalSimpleActionPerformed

    private void btnCondicionaldobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCondicionaldobleActionPerformed
        
        int num = Integer.parseInt( JOptionPane.showInputDialog(this, 
                                        "Escribe un numero entero") );
        
        if( num%2 == 0)
          JOptionPane.showMessageDialog(this, num + " es par");
        else
          JOptionPane.showMessageDialog(this, num + " es impar");  
        
    }//GEN-LAST:event_btnCondicionaldobleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCondicionalMultiple;
    private javax.swing.JButton btnCondicionaldoble;
    private javax.swing.JButton btnInstCondicionalSimple;
    private javax.swing.JButton btnInstruccioAsignacionESA;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
