
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author invitado
 */
public class FrmVentana extends javax.swing.JFrame {

    /**
     * Creates new form FrmVentana
     */
    public FrmVentana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnInstruccioAsignacionESA = new javax.swing.JButton();
        btnInstCondicionalSimple = new javax.swing.JButton();
        btnCondicionaldoble = new javax.swing.JButton();
        btnCondicionalMultiple = new javax.swing.JButton();
        btnCiclicaMientras = new javax.swing.JButton();
        btnCiclicaHacerMientras = new javax.swing.JButton();
        btnClicaDesde = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaTabla = new javax.swing.JTextArea();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hola Mundo");

        btnInstruccioAsignacionESA.setText("Asignacion ESA");
        btnInstruccioAsignacionESA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccioAsignacionESAActionPerformed(evt);
            }
        });

        btnInstCondicionalSimple.setText("Condicional Simple");
        btnInstCondicionalSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstCondicionalSimpleActionPerformed(evt);
            }
        });

        btnCondicionaldoble.setText("Condicion aldoble");
        btnCondicionaldoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCondicionaldobleActionPerformed(evt);
            }
        });

        btnCondicionalMultiple.setText("Condicional Multiple");
        btnCondicionalMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCondicionalMultipleActionPerformed(evt);
            }
        });

        btnCiclicaMientras.setText("Inst. Ciclica Mientras");
        btnCiclicaMientras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiclicaMientrasActionPerformed(evt);
            }
        });

        btnCiclicaHacerMientras.setText("Inst.Ciclica Hacer-Mientras");
        btnCiclicaHacerMientras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiclicaHacerMientrasActionPerformed(evt);
            }
        });

        btnClicaDesde.setText("Int. Clica Desde");
        btnClicaDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClicaDesdeActionPerformed(evt);
            }
        });

        txaTabla.setColumns(20);
        txaTabla.setRows(5);
        jScrollPane1.setViewportView(txaTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCiclicaMientras)
                    .addComponent(btnCiclicaHacerMientras)
                    .addComponent(btnClicaDesde)
                    .addComponent(btnInstruccioAsignacionESA)
                    .addComponent(btnInstCondicionalSimple)
                    .addComponent(btnCondicionaldoble)
                    .addComponent(btnCondicionalMultiple))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInstruccioAsignacionESA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInstCondicionalSimple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCondicionaldoble)
                        .addGap(13, 13, 13)
                        .addComponent(btnCondicionalMultiple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCiclicaMientras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCiclicaHacerMientras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClicaDesde)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInstruccioAsignacionESAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccioAsignacionESAActionPerformed
        // TODO add your handling code here:
        
        //llamada a una caja de dialogo de entrada.
        String nombre = JOptionPane.showInputDialog(this, "Escribe tu nombre: " );
        
        //llamada a una caja 
        String saludo = "Bienvenido " + nombre + " Adios";
        
        JOptionPane.showMessageDialog(this, saludo);
    }//GEN-LAST:event_btnInstruccioAsignacionESAActionPerformed

    private void btnInstCondicionalSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstCondicionalSimpleActionPerformed
        // TODO add your handling code here:
        int compra, boletos;
        
        
        
        compra = Integer.parseInt( JOptionPane.showInputDialog(this, 
                                        "¿cuál fue el monto de tu compla") );
        
        //priceso
        if( compra >= 1100 ){
            boletos = (compra-1000)/100;
            JOptionPane.showMessageDialog(this, "Obtienes " + boletos +  " boletos");
            
        }
       JOptionPane.showMessageDialog(this, "Gracias por tu compra ");
    }//GEN-LAST:event_btnInstCondicionalSimpleActionPerformed

    private void btnCondicionaldobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCondicionaldobleActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt( JOptionPane.showInputDialog(this, 
                                        "Escribe un numero entero") );
        
        if( num%2 == 0)
          JOptionPane.showMessageDialog(this, num + " es par");
        else
          JOptionPane.showMessageDialog(this, num + " es impar");  
    }//GEN-LAST:event_btnCondicionaldobleActionPerformed

    private void btnCondicionalMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCondicionalMultipleActionPerformed
         int dia = Integer.parseInt( JOptionPane.showInputDialog(this, 
                                                "Escrive un numero entero"));
        
        String cadenaDia ="";
        
        switch (dia){
            case 1: cadenaDia += " Domingo";
                break;
            case 2: cadenaDia += " Lunes";
                break;
            case 3: cadenaDia += " Martes";
                break;
            case 4: cadenaDia += " Miercoles";
               break; 
            case 5: cadenaDia += " Jueves";
                break;
            case 6: cadenaDia += " Viernes";
                break;
            case 7: cadenaDia += " Sabado";
                break;
            default: cadenaDia += " ERROR";
        }
        JOptionPane.showMessageDialog(this, cadenaDia);
    }//GEN-LAST:event_btnCondicionalMultipleActionPerformed

    private void btnCiclicaMientrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiclicaMientrasActionPerformed
        
        
        
    }//GEN-LAST:event_btnCiclicaMientrasActionPerformed

    private void btnCiclicaHacerMientrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiclicaHacerMientrasActionPerformed
        
        
    }//GEN-LAST:event_btnCiclicaHacerMientrasActionPerformed
/*  -Variable de control.
            -Inicializar la variable de control.
            -Condicion de pertenecia.
            -Modificacion de la variable de control.
            
        */
    private void btnClicaDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClicaDesdeActionPerformed
        byte cont;
        String cadena = "";
        
        byte num = Byte.parseByte( JOptionPane.showInputDialog(this, 
                            "Escrive el numero de la tabla de multiplicar"));
        
       for( cont=1; cont<=10; cont++)
           cadena += num + "x" + cont + " = " + num*cont + "\n"; 
           
       txaTabla.setText(cadena);
       
        
    }//GEN-LAST:event_btnClicaDesdeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCiclicaHacerMientras;
    private javax.swing.JButton btnCiclicaMientras;
    private javax.swing.JButton btnClicaDesde;
    private javax.swing.JButton btnCondicionalMultiple;
    private javax.swing.JButton btnCondicionaldoble;
    private javax.swing.JButton btnInstCondicionalSimple;
    private javax.swing.JButton btnInstruccioAsignacionESA;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaTabla;
    // End of variables declaration//GEN-END:variables
}
